'use strict';

// Harness-agnostic status sidecar — replaces the Claude-only OSC-777 sentinel.
//
// Claude Code could ride its own pty in-band via the hook `terminalSequence` output field, which
// needed NO correlation: the pane that received the sentinel owned it. Codex has zero occurrences
// of terminalSequence, so its hook output cannot reach the terminal stream at all. The channel must
// be out-of-band, and out-of-band means correlation becomes a real problem.
//
// Both harnesses unify on this one path rather than keeping two mechanisms for one concept in a
// renderer layer that is not unit-tested.
//
//   pty spawn  ->  CLI  ->  hook child (token baked into its command line)
//                                 |
//                                 v
//              <userData>/session-events/<token>.jsonl   (append-only)
//                                 |
//                        debounced fs.watch + safety poll
//                                 |
//                     main: per-file byte offset, token -> session
//                                 v
//                          renderer via existing IPC

const fs = require('fs');
const path = require('path');

const DIR_NAME = 'session-events';

// Single definition of what a valid token looks like, shared by the writer-side validators below
// AND interpolated into the generated emitter (see EMITTER) — one rule, not two definitions that
// can drift. hookSpawnConfig and cleanup() both string-concatenate `token` into a filesystem path
// ('mavis-hooks-' + token + '.json', token + '.jsonl'); an unvalidated token containing '../' can
// walk that path outside userData entirely — refuse rather than guess.
const TOKEN_PATTERN = '^[A-Za-z0-9-]+$';

function isValidToken(token) {
  return typeof token === 'string' && new RegExp(TOKEN_PATTERN).test(token);
}

// One emitter, both vocabularies. Claude's event names are PascalCase, Codex's are snake_case, and
// they do not overlap, so a single lookup table serves both with no harness flag needed.
//
// Codex has NO StopFailure analogue: an errored turn is derived from the pty exit code instead.
// Stated rather than papered over.
const EMITTER = `'use strict';
// AUTO-GENERATED by Mavis-Terminal (src/session-events.js) — regenerated each launch, do not edit.
// Reads an agent hook event on stdin, appends one normalized line to this session's sidecar file.
// argv[2] is the session token, argv[3] is the events directory — both baked into the hook command
// at spawn time (see buildHookCommand) because THIS SCRIPT RUNS AS A CHILD OF THE CLI'S HOOK
// MECHANISM, not of Mavis-Terminal directly, so env var inheritance into it is unverified on both
// harnesses. Without a token we exit silently — a session is NEVER blocked on notification plumbing.
const fs = require('fs');
const path = require('path');
const STATES = {
  Stop: 'done', StopFailure: 'error', PreToolUse: 'busy',
  stop: 'done', permission_request: 'await', pre_tool_use: 'busy',
};
let raw = '';
process.stdin.on('data', function (d) { raw += d; });
process.stdin.on('end', function () {
  try {
    const token = process.argv[2];
    if (!token || !/${TOKEN_PATTERN}/.test(token)) return;
    let j = {};
    try { j = JSON.parse(raw || '{}'); } catch (e) { j = {}; }
    const ev = j.hook_event_name;
    let state = STATES[ev] || null;
    // Claude's Notification fires for several types; only a permission prompt is a real pause.
    // idle_prompt is deliberately ignored — Stop already covers turn-end, so acting on it too
    // would double-fire.
    if (ev === 'Notification') state = j.notification_type === 'permission_prompt' ? 'await' : null;
    if (!state) return;
    // argv[3] is the events dir baked into the hook command and always wins; MAVIS_EVENTS_DIR is a
    // best-effort fallback only, for direct invocation outside the normal hook path.
    const dir = process.argv[3] || process.env.MAVIS_EVENTS_DIR;
    if (!dir) return;
    fs.mkdirSync(dir, { recursive: true });
    fs.appendFileSync(path.join(dir, token + '.jsonl'),
      JSON.stringify({ state: state, at: Date.now() }) + '\\n');
  } catch (e) { /* never block the session */ }
});
`;

function eventsDir(userDataDir) {
  return path.join(userDataDir, DIR_NAME);
}

function emitterPath(userDataDir) {
  return path.join(userDataDir, 'mavis-session-event.js');
}

// node "<emitter>" <token> "<eventsDir>" — the events dir travels on the command line for the same
// reason the token does: the emitter runs as a child of the CLI's hook mechanism, not of us, so env
// var inheritance into it is unverified on both harnesses (and Codex's shell_environment_policy
// could sanitize it). Baking both into argv works regardless of inheritance.
// JSON.stringify quotes/escapes each path for both a command string and a JSON settings file.
// Requires node on PATH.
function buildHookCommand(emitter, token, eventsDirPath) {
  return 'node ' + JSON.stringify(emitter) + ' ' + token + ' ' + JSON.stringify(eventsDirPath);
}

// Write the emitter and prepare the events dir. Returns the emitter path, or null on any failure
// (in which case no hook config is produced and status falls back to tui-detect / absent).
function ensure(userDataDir) {
  try {
    if (!userDataDir) return null;
    const p = emitterPath(userDataDir);
    fs.writeFileSync(p, EMITTER);
    fs.mkdirSync(eventsDir(userDataDir), { recursive: true });
    // Best-effort fallback only, not the hot path: the emitter runs as a child of the CLI's hook
    // mechanism (see buildHookCommand), not of this process, so this env var is not guaranteed to
    // reach it. The events dir the emitter actually relies on is baked into the hook command's
    // argv instead. This is set for the rare direct-invocation case (e.g. manual debugging).
    process.env.MAVIS_EVENTS_DIR = eventsDir(userDataDir);
    return p;
  } catch {
    return null;
  }
}

// Per-spawn hook wiring. Claude takes an additive --settings JSON; Codex takes -c overrides,
// because it refuses project-local config from an untrusted directory and the brain root is not in
// its [projects] trust list.
function hookSpawnConfig(harnessId, token, userDataDir) {
  try {
    const dir = userDataDir || process.env.MAVIS_USER_DATA;
    // isValidToken guards every filesystem path built from `token` below ('mavis-hooks-' + token +
    // '.json') against path traversal ('../../x') — refuse rather than guess. The generated emitter
    // enforces the identical rule (via TOKEN_PATTERN) on the read side; this is the write side.
    if (!dir || !isValidToken(token)) return {};
    const emitter = emitterPath(dir);
    if (!fs.existsSync(emitter)) return {};
    const command = buildHookCommand(emitter, token, eventsDir(dir));

    if (harnessId === 'codex') return { hookCommand: command };

    // PreToolUse is BLOCKING on Claude — the CLI waits on the hook child before every single tool
    // call, so a 60-tool turn would serialize 60 cold `node` process starts. It is Codex's ONLY
    // status channel (no in-band terminalSequence there — see the module banner above), which is
    // why hookOverrides above wires pre_tool_use unconditionally for Codex. Claude has no such gap:
    // its existing onData/isWorking scan already derives 'busy' without it, and pre-branch
    // mavis-hooks.js registered only Stop, StopFailure and Notification. See Finding 3, 2026-07-26
    // whole-branch review.
    const entry = [{ hooks: [{ type: 'command', command }] }];
    const settings = { hooks: { Stop: entry, StopFailure: entry, Notification: entry } };
    // One settings file PER TOKEN: the token is baked into the command, so sessions cannot share.
    const p = path.join(dir, 'mavis-hooks-' + token + '.json');
    fs.writeFileSync(p, JSON.stringify(settings, null, 2));
    return { hookSettingsPath: p };
  } catch {
    return {};
  }
}

// Remove a single session's sidecar file + per-token settings on close. Same traversal guard as
// hookSpawnConfig: refuse an invalid token rather than string-concatenate it into a path we then
// unlink — cleanup() deletes files, so a bad token here is a worse outcome than a bad token there.
function cleanup(userDataDir, token) {
  if (!userDataDir || !isValidToken(token)) return;
  for (const p of [
    path.join(eventsDir(userDataDir), token + '.jsonl'),
    path.join(userDataDir, 'mavis-hooks-' + token + '.json'),
  ]) {
    try { fs.unlinkSync(p); } catch { /* already gone */ }
  }
}

// Clear leftovers from a crash. Returns how many files were removed.
function sweep(userDataDir) {
  let n = 0;
  try {
    const dir = eventsDir(userDataDir);
    for (const f of fs.readdirSync(dir)) {
      try { fs.unlinkSync(path.join(dir, f)); n++; } catch { /* ignore */ }
    }
    for (const f of fs.readdirSync(userDataDir)) {
      if (/^mavis-hooks-.+\.json$/.test(f)) {
        try { fs.unlinkSync(path.join(userDataDir, f)); } catch { /* ignore */ }
      }
    }
  } catch { /* dir missing */ }
  return n;
}

// Per-file byte offsets, not re-reads. Windows fs.watch coalesces rapid events, so we re-read from
// the last offset on ANY event and additionally poll at a low frequency — the same belt-and-braces
// the Changes view already uses.
function createReader({ userDataDir, onState, pollMs = 4000, debounceMs = 60 } = {}) {
  const dir = eventsDir(userDataDir);
  const offsets = new Map();   // token -> bytes consumed
  const partials = new Map();  // token -> unterminated trailing text
  let watcher = null;
  let poll = null;
  let timer = null;

  const readOne = (token) => {
    const file = path.join(dir, token + '.jsonl');
    let stat;
    try { stat = fs.statSync(file); } catch (e) {
      // ENOENT only means "genuinely gone" (deleted between readdirSync and here — a race, since
      // the routine forget-a-deleted-token path is the sweep at the end of tick() below, which a
      // file missing from the CURRENT listing never reaches readOne to hit). Any OTHER error
      // (EBUSY, permission blip, transient I/O error from an AV lock, etc.) means the file is
      // still there and we just could not stat it THIS tick — treat it exactly like the
      // openSync/readSync failure below and leave offsets/partials untouched so the next tick
      // retries from the correct byte. Clearing them here would replay the token's entire history
      // and double-deliver every event already sent for it. Do not collapse these two branches:
      // they look identical but "gone" and "temporarily unreadable" require opposite responses.
      if (e && e.code === 'ENOENT') {
        offsets.delete(token);
        partials.delete(token);
      }
      return;
    }
    const from = offsets.get(token) || 0;
    if (stat.size === from) return;
    // Truncated or replaced — start over rather than reading garbage from a stale offset.
    const start = stat.size < from ? 0 : from;
    let chunk = '';
    try {
      const fd = fs.openSync(file, 'r');
      try {
        const buf = Buffer.alloc(stat.size - start);
        fs.readSync(fd, buf, 0, buf.length, start);
        chunk = buf.toString('utf8');
      } finally { fs.closeSync(fd); }
    } catch { return; }
    offsets.set(token, stat.size);

    const text = (partials.get(token) || '') + chunk;
    const lines = text.split('\n');
    // A trailing fragment with no newline is an incomplete append; hold it for the next tick.
    partials.set(token, lines.pop());
    for (const line of lines) {
      const s = line.trim();
      if (!s) continue;
      let j = null;
      try { j = JSON.parse(s); } catch { continue; }
      if (!j || !j.state) continue;
      try { onState({ token, state: String(j.state), at: j.at || null }); } catch { /* ignore */ }
    }
  };

  const tick = () => {
    let names = [];
    try { names = fs.readdirSync(dir); } catch { return; }
    const present = new Set();
    for (const n of names) {
      if (!n.endsWith('.jsonl')) continue;
      const token = n.slice(0, -6);
      // Same guard as the write side (hookSpawnConfig/cleanup): a filename we did not create
      // ourselves is untrusted input, and it feeds a path.join() below via readOne. Skip rather
      // than trust the directory listing.
      if (!isValidToken(token)) continue;
      present.add(token);
      readOne(token);
    }
    // A token we were tracking that no longer has a file (cleanup() on session close, or sweep())
    // never reaches readOne above — it only visits names CURRENTLY in the directory. Forget it here
    // instead, so a recycled/recreated token starts at offset zero rather than being silently
    // skipped by a stale offset left over from before the delete.
    for (const token of new Set([...offsets.keys(), ...partials.keys()])) {
      if (!present.has(token)) { offsets.delete(token); partials.delete(token); }
    }
  };

  const schedule = () => {
    clearTimeout(timer);
    timer = setTimeout(tick, debounceMs);
  };

  return {
    start() {
      try { fs.mkdirSync(dir, { recursive: true }); } catch { /* ignore */ }
      try { watcher = fs.watch(dir, {}, schedule); } catch { watcher = null; }
      poll = setInterval(tick, pollMs);
      if (poll.unref) poll.unref();
      tick();
    },
    stop() {
      try { if (watcher) watcher.close(); } catch { /* ignore */ }
      watcher = null;
      clearInterval(poll);
      clearTimeout(timer);
    },
    _tick: tick,
  };
}

module.exports = {
  ensure, eventsDir, emitterPath, buildHookCommand, hookSpawnConfig, cleanup, sweep, isValidToken, EMITTER,
  createReader,
};
